AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a private S3 bucket for CodeGuru Reviewer'

Resources:
  CodeGuruReviewerBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - 'codeguru-reviewer'
          - !Select 
            - 0
            - !Split 
              - '-'
              - !Select 
                - 2
                - !Split 
                  - '/'
                  - !Ref 'AWS::StackId'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: 'Name of the created S3 bucket'
    Value: !Ref CodeGuruReviewerBucket
  BucketARN:
    Description: 'ARN of the created S3 bucket'
    Value: !GetAtt CodeGuruReviewerBucket.Arn