name: CodeGuru

on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - main

permissions:
  id-token: write   # Required for requesting the JWT
  contents: write   # Required for actions/checkout
  security-events: write
  pull-requests: write
  repository-projects: write
  actions: read

env:
  AWS_REGION: ap-southeast-2  # Change this to your preferred region


jobs:
  codeugru:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository and provide your AWS credentials
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OICD_ROLE }}
          role-session-name: gh-${{ github.repository_id}}-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get CodeGuru Stack Outputs
        id: codeguru
        run: |
          CODEGURU_BUCKET=$(aws cloudformation describe-stacks --stack-name codeguru-s3-bucket-stack --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" --output text 2>/dev/null) || true
          echo "codeguru-bucket=${CODEGURU_BUCKET}" >> $GITHUB_OUTPUT
          if [ -z "$CODEGURU_BUCKET" ]; then
            echo "bucket_found=false" >> $GITHUB_OUTPUT
          else
            echo "bucket_found=true" >> $GITHUB_OUTPUT
          fi

      # Step 2: Add CodeGuru Reviewer Action
      - name: CodeGuru Reviewer
        if: steps.codeguru.outputs.bucket_found == 'true'
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          s3_bucket: ${{ steps.codeguru.outputs.codeguru-bucket }} 
        continue-on-error: true
      
      # Step 3: Upload results into GitHub
      - name: Upload review result
        if: steps.codeguru.outputs.bucket_found == 'true' && ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codeguru-results.sarif.json
        continue-on-error: true

      - name: Upload the sarif file to Artifacts
        if: steps.codeguru.outputs.bucket_found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: codeguru-results.sarif.json
          path: codeguru-results.sarif.json
