name: Deploy ECR repo

on:
  workflow_call:
    outputs:
      bucket-name:
        description: "The name of the created S3 bucket"
        value: ${{ jobs.deploy-s3-bucket.outputs.bucket-name }}

env:
  AWS_REGION: ap-southeast-2 
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  deploy-ecr-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.OICD_ROLE }}
        role-session-name: gh-${{ github.repository_id}}-${{ github.sha }}
        aws-region: ${{ env.AWS_REGION }}

  
    - name: Deploy ECR Repo
      uses: aws-actions/aws-cloudformation-github-deploy@master
      with:
        name: ecr-repo-${{ env.ECR_REPOSITORY }}
        template: cloudformation/ecr.yml 
        capabilities: CAPABILITY_IAM
        role-arn: ${{ secrets.DEPLOY_ROLE }}
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          RepositoryName="${{ env.ECR_REPOSITORY }}"
